src/hidlroute/urls.py
#    Hidl Route - opensource vpn management system
#    Copyright (C) 2023 Dmitry Berezovsky, Alexander Cherednichenko
#
#    Hidl Route is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Hidl Route is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""hidlroute URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path("sso-social/", include("social_django.urls", namespace="social")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("2fa/", include(tf_urls)),
    path("selfservice/", include("hidlroute.vpn.urls", namespace="selfservice")),
]

if settings.DEBUG_TOOLBAR:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

if settings.BRUTE_FORCE_PROTECTION:
    urlpatterns += [
        path("defender/", include("hidlroute.web.urls_defender", namespace="defender")),
    ]

urlpatterns += [
    path("", admin.site.urls),
]

src/hidlroute/vpn/urls.py
#    Hidl Route - opensource vpn management system
#    Copyright (C) 2023 Dmitry Berezovsky, Alexander Cherednichenko
#
#    Hidl Route is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Hidl Route is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.urls import path

from hidlroute.vpn import views

app_name = "hidl_core"
urlpatterns = [
    path("devices/", views.DeviceVPNListView.as_view(), name="devices_list"),
    path("server/<int:server_id>/add_device/", views.device_add, name="device_add"),
    path("edit_device/<int:device_id>/", views.device_edit, name="device_edit"),
    path("device/<int:device_id>/reveal_config/", views.device_reveal_config, name="reveal_config"),
]

src/hidlroute/web/templates/tags/current_servers.html
{% load i18n %}
{#<div class="card card-primary">#}
{#    <div class="card-header">{% trans "My Servers" %}</div>#}
{#    <div class="card-body" style="display:flex; flex-direction: row;">#}
{#        {% for s in servers %}#}
{#            <div style="background:yellow; width: 200px; margin: 0 15px;">#}
{#                {{ s.name }}{{ s.interface_name }}#}
{#                <a href="{% url "selfservice:devices_list" %} ">Edit devices</a>#}
{#            </div>#}
{#        {% endfor %}#}
{#    </div>#}
{#</div>#}
<div class="row mb-3 mt-2">
    {% for pair in servers_and_devices %}
        <div class="col-md-4">
            <div class="card card-widget widget-server-with-devices">
                <div class="card-header color-{{ pair.color_class }}">
                    <div class="icon">
                        <i class="fas fa-server" aria-hidden="true"></i>
                    </div>
                    {% if pair.server.status.state.name != "RUNNING" %}
                        <div class="offline-badge badge badge-danger">Offline</div>
                    {% endif %}
                    <h3 class="server-name">{{ pair.server.name }}</h3>
                    <h5 class="server-description">{{ pair.server.subnet.cidr }}</h5>
                </div>
                <div class="card-footer no-padding">
                    {% if pair.devices %}
                        <ul class="nav nav-stacked">
                            {% for d in pair.devices %}
                                <li>
                                    <a href="{% url "selfservice:device_edit" d.pk %}">{{ d.name }}
                                        <span class="mt-1 pull-right text-muted badge">{{ d.ip_address.ip }}</span>
                                        {#                                    <span class="pull-right badge bg-red">Blocked</span>#}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <div class="mt-2 mb-2 text-center">
                            <div class="m-2 font-italic text-muted">
                                {% trans "You do not have any devices" %}
                            </div>
                            <a class="btn btn-sm btn-link text-success"
                               href="{% url "selfservice:device_add" pair.server.pk %}">
                                <i class="fa fa-plus"></i>
                                {% trans "Add device" %}
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% empty %}
        <div class="text-muted text-center">
            {% trans "You don't have access to any servers" %}
        </div>
    {% endfor %}
</div>